Properly indent bonnyci shell command
I think i got this wrong, zuul is failing to load it and I'm pretty sure
it's because it was under indented.

Change-Id: I4a021e34f7435a9e19896929a6b549f8545af40a
Signed-off-by: Jamie Lennox <jamielennox@gmail.com>

diff --git a/playbooks/bonnyci.yaml b/playbooks/bonnyci.yaml
--- a/playbooks/bonnyci.yaml
+++ b/playbooks/bonnyci.yaml
@@ -1,24 +1,24 @@
 - hosts: all
   tasks:
     - shell: |
-      #!/bin/bash -xe
+        #!/bin/bash -xe
 
-      if [[ ! -f .bonnyci/run.sh ]]; then
-          echo "ERROR: No test script found at .bonnyci/run.sh, skipping"
-          exit 1
-      elif [[ ! -x .bonnyci/run.sh ]]; then
-          echo "ERROR: Test script found at .bonnyci/run.sh but it is not executable"
-          exit 1
-      fi
+        if [[ ! -f .bonnyci/run.sh ]]; then
+            echo "ERROR: No test script found at .bonnyci/run.sh, skipping"
+            exit 1
+        elif [[ ! -x .bonnyci/run.sh ]]; then
+            echo "ERROR: Test script found at .bonnyci/run.sh but it is not executable"
+            exit 1
+        fi
 
-      export BONNYCI_TEST_PIPELINE={pipeline}
-      export BONNYCI_TEST_LOG_DIR="$(pwd)/logs"
-      mkdir -p $BONNYCI_TEST_LOG_DIR
+        export BONNYCI_TEST_PIPELINE={pipeline}
+        export BONNYCI_TEST_LOG_DIR="$(pwd)/logs"
+        mkdir -p $BONNYCI_TEST_LOG_DIR
 
-      if ./.bonnyci/run.sh; then
-          echo ".bonnyci/run.sh test(s) passed :)"
-          exit 0
-      else
-          echo ".bonnyci/run.sh test(s) failed :("
-          exit 1
-      fi
+        if ./.bonnyci/run.sh; then
+            echo ".bonnyci/run.sh test(s) passed :)"
+            exit 0
+        else
+            echo ".bonnyci/run.sh test(s) failed :("
+            exit 1
+        fi
